### ISSUE TITLE
Types are not case sensitive

### ISSUE THREAD

**Issue by digisolu** [denishpatel/pg-clone-schema#148]
Thank you for this great project. It helps me a lot when working with pg and schemas.

But in my current OpenSource Project I ran into the issue, that the cloned types were not written correctly.

Original:
![image](https://github.com/user-attachments/assets/68e6d610-1ac7-490c-996b-b33a4f44abd0)

Clone:
![image](https://github.com/user-attachments/assets/55decc16-f091-4109-a42e-966a4854bf41)

In your code it looks like the names for the types are not quoted.

**Comment by MichaelDBA** [comment]
I am able to validate it as a bug. Working on it...

**Comment by MichaelDBA** [comment]
Hi, @digisolu 
Fixed, try the latest code and let me know.

**Comment by digisolu** [comment]
Hi @MichaelDBA,

it's not working so far.

The references in the create table statements are still not quoted.

SQL-Error [P0001]: ERROR: Version: 2.17 December 7, 2024  Action: Tables  CurrentSP: "$user", public  oldSP="$user", public  newSP=template  Diagnostics: line=PL/pgSQL function clone_schema(text,text,cloneparms[]) line 883 at EXECUTE. 42704. type "newSchemaTest.addresstype" does not exist

PL/pgSQL function clone_schema(text,text,cloneparms[]) line 3263 at RAISE

The types are ok now, the references not.

**Comment by MichaelDBA** [comment]
Yes, the problem is bigger than I thought.  Working on it now...  It was something actually broken with pg_get_tabledef(), a called function within clone_schema.  This is a separate project owned by me and I am fixing that first, then  reimporting it back into clone_schema.

**Comment by MichaelDBA** [comment]
Hi @digisolu 
Please get the latest code and try again.

**Comment by digisolu** [comment]
@MichaelDBA 

Seems to work now, no more error so far. 
THX a lot.
