### ISSUE TITLE
Clone doesn't propertly quote enum types `

### ISSUE THREAD

**Issue by johnpena** [denishpatel/pg-clone-schema#61]
When creating a table with a field that has an enum type, the enum type isn't properly quoted and the clone can fail when the enum type has a capital letter. For example, the clone_schema function tries to run:

```sql
CREATE TABLE newschema.SomeTable (
  field_with_enum newschema.SomeEnumField NOT NULL DEFAULT 'NONE'::"SomeEnumField",
)
```

Which results in the error:

`PL/pgSQL function clone_schema(text,text,boolean,boolean) line 329 at EXECUTE. 42804. column "status" is of type newschema.someenumfield but default expression is of type "SomeEnumField" (SQLSTATE P0001)`

**Comment by CarelFdeWaal** [comment]
Possible related issue. Error is bit different:
```
PL/pgSQL function clone_schema(text,text,boolean,boolean) line 329 at EXECUTE. 42704. type "newSchema.AccessTokenType" does not exist
```
The enum does exist on the origin schema:
```
 \dT+ "AccessTokenType"
                                             List of data types
 Schema |       Name        |  Internal name  | Size | Elements |  Owner   | Access privileges | Description 
--------+-------------------+-----------------+------+----------+----------+-------------------+-------------
 public | "AccessTokenType" | AccessTokenType | 4    | CLI     +| postgres |                   | 
        |                   |                 |      | WORKER   |          |                   | 
(1 row)
```

Note I did see this warning:
```
WARNING:   Table (AccessToken) has column(s) with user-defined types so using get_table_ddl() instead of CREATE TABLE LIKE construct.
```

**Comment by MichaelDBA** [comment]
investigating...

**Comment by MichaelDBA** [comment]
Fixed.
Fixed more search_path problems. 

- Modified get_table_ddl() to hard code search_path to public to force explicit qualified objects. 
- Using set_config() for empty search_path string instead of trying to set empty string directly and incorrectly.

**Comment by MichaelDBA** [comment]
@johnpena, @CarelFdeWaal , please validate before I close this issue.

**Comment by johnpena** [comment]
@MichaelDBA thanks for the quick work on this, unfortunately I'm still experiencing the same issue. Let me know if there's more detail I could add that would be helpful.

**Comment by MichaelDBA** [comment]
@johnpena, can you reply to my last ask of you?

**Comment by johnpena** [comment]
Apologies for the slow response. I was indeed using the public schema and I expect that was the source of the issues.

**Comment by MichaelDBA** [comment]
Well there were definitely things I fixed in this regard.  So Im gonna close this for now.
